on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - run: ffmpeg -i input.avi output.mkv
      - run: npm i dotenv discord.js discord-player @discordjs/voice @discordjs/rest @discordjs/opus @discordjs/builders
      - run: node index.js load
        env:
          CI: true
          TOKEN: ${{ secrets.TOKEN }}
      - run: node index.js
        env:
          CI: true
          TOKEN: ${{ secrets.TOKEN }}